# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('name', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=45, null=True)),
                ('description', models.CharField(blank=True, max_length=45, null=True)),
                ('targeted_muscle', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'Exercise',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('name', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('calories', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('carbohydrate', models.IntegerField()),
            ],
            options={
                'db_table': 'Nutrition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(blank=True, db_column='Profile', max_length=1000, null=True)),
            ],
            options={
                'db_table': 'Trainer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('d_o_b', models.DateField(db_column='d.o.b')),
                ('username', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('password', models.CharField(db_column='Password', max_length=45)),
                ('type', models.CharField(db_column='type', max_length=45)),
            ],
            options={
                'db_table': 'User',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('workoutid', models.IntegerField(db_column='workoutID', primary_key=True, serialize=False)),
                ('exercise', models.CharField(blank=True, max_length=45, null=True)),
                ('reps', models.CharField(blank=True, max_length=45, null=True)),
                ('sets', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'Workout',
                'managed': False,
            },
        ),
    ]
